### ISSUE TITLE
Tshock Superadmin error

### ISSUE THREAD

**Issue by IWasAndrerstajn** [Pryaxis/TShock#1523]
## TShock version
4.3.24

2017-12-03 23:34:28 - Utils: INFO: SheMAIL executed: /auth 3017859.
2017-12-03 23:35:23 - Commands: ERROR: TShockAPI.DB.UserManagerException: AddUser SQL returned an error (Abort due to constraint violation
UNIQUE constraint failed: Users.Username) ---> Mono.Data.Sqlite.SqliteException: Abort due to constraint violation
UNIQUE constraint failed: Users.Username
   at Mono.Data.Sqlite.SQLite3.Reset(SqliteStatement stmt)
   at Mono.Data.Sqlite.SQLite3.Step(SqliteStatement stmt)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at TShockAPI.DB.DbExt.Query(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.DB.UserManager.AddUser(User user)
   --- End of inner exception stack trace ---
   at TShockAPI.DB.UserManager.AddUser(User user)
   at TShockAPI.Commands.ManageUsers(CommandArgs args)

**Comment by hakusaro** [comment]
I'm guessing you tried to add a user that already exists after authenticating. However, this is not the place for support. Join discord, or join the forums for more debugging and help.
