### ISSUE TITLE
Continuous Crashing

### ISSUE THREAD

**Issue by enderking470** [Pryaxis/TShock#1664]
* TShock version: 2.1.0.0
* TShock build number (if known):

#### Any stack traces or error messages (if known)?

```
[03/27/19 09:43:43] [Server API] Verbose: TerrariaApi - Server v2.1.0.0 started.
[03/27/19 09:43:43] [Server API] Verbose: 	Command line: "C:\Users\john smith\Downloads\tshock_4.3.25\TerrariaServer.exe" 
[03/27/19 09:43:43] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[03/27/19 09:43:43] [Server API] Verbose: 	Mono: False
[03/27/19 09:43:43] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at TShockAPI.ConfigFile.Write(Stream stream)
   at TShockAPI.ConfigFile.Write(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at TerrariaApi.Server.HookManager.InitialiseAPI()
```

**Comment by sr229** [comment]
Seems it can't load a part of the standard library. What's your .NET Framework version?

**Comment by enderking470** [comment]
Microsoft .NET Framework 4.7.2

**Comment by sr229** [comment]
CC @bartico6

**Comment by bartico6** [comment]
![Installer](https://i.quake.tf/1553907870-64531157.png)
![MSCorlib version](https://i.quake.tf/1553907901-14344023.png)
Doesn't happen here on a clean compile of v4.3.25. You likely have a corrupted .NET installation.

**Comment by QuiCM** [comment]
@enderking470 is this still occurring for you after verifying your dotnet installation?
