### ISSUE TITLE
Travis keeps failing

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1687]
We should probably fix it at some point. Or remove it as a required build.

Errors such as:
https://travis-ci.org/Pryaxis/TShock/builds/593056609#L4234
```
Traceback (most recent call last):

  File "./scripts/create_release.py", line 191, in <module>

    upload_artifacts()

  File "./scripts/create_release.py", line 128, in upload_artifacts

    os.mkdir(os.environ.get('TRAVIS_BRANCH', 'test-branch'))

OSError: [Errno 2] No such file or directory: 'all-contributors/add-sgkoishi'

The command "python ./scripts/create_release.py" exited with 1.
```

https://travis-ci.org/Pryaxis/TShock/builds/635502504#L1594
```
Installed:

    1 package(s) to packages.config projects

Traceback (most recent call last):

  File "./scripts/create_release.py", line 184, in <module>

    update_terraria_source()

  File "./scripts/create_release.py", line 144, in update_terraria_source

    subprocess.check_call(['nuget', 'restore', 'TerrariaServerAPI/'])

  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['nuget', 'restore', 'TerrariaServerAPI/']' returned non-zero exit status 1

The command "python ./scripts/create_release.py" exited with 1.
```

and
https://travis-ci.org/Pryaxis/TShock/builds/647518538#L1888
```
Traceback (most recent call last):

  File "./scripts/create_release.py", line 187, in <module>

    build_software()

  File "./scripts/create_release.py", line 177, in build_software

    raise CalledProcessError(release_proc.returncode)

NameError: global name 'CalledProcessError' is not defined

The command "python ./scripts/create_release.py" exited with 1.
```

**Comment by hakusaro** [comment]
This is probably because of python2/3 being different if I had to guess. I would really prefer we use GitHub but it may not be possible if we can’t pin all of the resources so the builds complete successfully more than once a year.

**Comment by hakusaro** [comment]
I think this is fixed btw @QuiCM

**Comment by QuiCM** [comment]
Cheers
