### ISSUE TITLE
Stuck on "Requesting Tile Data" when trying to connect to my server for v1.4.0.3

### ISSUE THREAD

**Issue by Renkyz** [Pryaxis/TShock#1832]
* TShock version: TShock 4.4.0 Pre-release 5 for Terraria 1.4.0.3
* TShock build number (if known):

#### Any screenshots?
https://imgur.com/a/TkfZ1on

#### Any log messages from files that end in `.log` or `.txt`?
2020-05-21 14:40:07 - TextLog: INFO: TShock 4.4.0.0 (Go to sleep Patrikkk, Icy, Chris, Death, Axeel, Zaicon, hakusaro, and Yoraiz0r <3) now running.
2020-05-21 14:40:07 - TShock: INFO: AutoSave Enabled
2020-05-21 14:40:07 - TShock: INFO: Backups Disabled
2020-05-21 14:40:07 - TShock: INFO: Welcome to TShock for Terraria!
2020-05-21 14:40:07 - TShock: INFO: TShock comes with no warranty & is free software.
2020-05-21 14:40:07 - TShock: INFO: You can modify & distribute it under the terms of the GNU GPLv3.
2020-05-21 14:40:39 - GetDataHandlers: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.TSPlayer.HasPermission(String permission)
   at TShockAPI.Bouncer.OnGetSection(Object sender, GetSectionEventArgs args)
   at TShockAPI.HandlerList`1.Invoke(Object sender, T e)
   at TShockAPI.GetDataHandlers.OnGetSection(TSPlayer player, MemoryStream data, Int32 x, Int32 y)
   at TShockAPI.GetDataHandlers.HandleGetSection(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)
2020-05-21 14:42:39 - TShock: INFO: Renkyz The 2nd disconnected.

#### What plugins and what versions of those plugins are you running?
Vanillafier v1.1.0.0 (by Pryaxis)

**Comment by Renkyz** [comment]
Forgot to add, I downloaded the vanilla server from terraria.org, set that up with the exact same world and it's working fine. So figured it must be a TShock issue. It was working just fine for me in Pre 1 release.

**Comment by Renkyz** [comment]
As of Pre 6, my server is now working. Closing this issue.
