### ISSUE TITLE
Crash when use plugin.

### ISSUE THREAD

**Issue by JottaR** [Pryaxis/TShock#2243]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: 15
* TShock build number (if known): 4.4.0 (15)

#### Reproduction steps (if applicable)?

1. Some step
2. Some other step
3. Some bigger step
4. This is the problem

#### Any stack traces or error messages (if known)?

```
[03/14/21 07:50:55] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Permabuffs V2.dll". ---> System.InvalidOperationException: Could not create an instance of plugin class "Permabuffs_V2.Permabuffs". ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Permabuffs_V2.Permabuffs' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Permabuffs_V2.Config.Read(String path)
   at Permabuffs_V2.Permabuffs..cctor()
   --- End of inner exception stack trace ---
   at Permabuffs_V2.Permabuffs..ctor(Main game)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 316
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 324
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 333
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 117
   at TerrariaApi.Server.HookManager.InitialiseAPI() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HookManager.cs:line 27
[03/14/21 07:52:49] [Server API] Error: ===================================================================================
[03/14/21 07:52:49] [Server API] Error: An unhandled exception has occured in TSAPI, and a crash report will be generated
[03/14/21 07:52:49] [Server API] Error: Generating a crash report, please wait...
[03/14/21 07:52:50] [Server API] Error: Could not generate a crash report.
[03/14/21 07:52:50] [Server API] Error: Please upload the crash file and report it at http://tshock.co/
[03/14/21 07:52:50] [Server API] Error: The process will terminate.
[03/14/21 07:52:50] [Server API] Error: ===================================================================================
[03/14/21 07:54:25] [Server API] Verbose: TerrariaApi - Server v2.1.0.0 started.
[03/14/21 07:54:25] [Server API] Verbose: 	Command line: "C:\Users\Juliano\Desktop\T.Terraria Server\TerrariaServer.exe" 
[03/14/21 07:54:25] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/14/21 07:54:25] [Server API] Verbose: 	Mono: False
[03/14/21 07:54:26] [Server API] Info: Plugin TShock v4.4.0.0 (by The TShock Team) initiated.
[03/14/21 07:54:36] [Server API] Verbose: TerrariaApi - Server v2.1.0.0 started.
[03/14/21 07:54:36] [Server API] Verbose: 	Command line: "C:\Users\Juliano\Desktop\T.Terraria Server\TerrariaServer.exe" 
[03/14/21 07:54:36] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/14/21 07:54:36] [Server API] Verbose: 	Mono: False
[03/14/21 07:54:36] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Permabuffs V2.dll". ---> System.InvalidOperationException: Could not create an instance of plugin class "Permabuffs_V2.Permabuffs". ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Permabuffs_V2.Permabuffs' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Permabuffs_V2.Config.Read(String path)
   at Permabuffs_V2.Permabuffs..cctor()
   --- End of inner exception stack trace ---
   at Permabuffs_V2.Permabuffs..ctor(Main game)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 316
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 324
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 333
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 117
   at TerrariaApi.Server.HookManager.InitialiseAPI() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HookManager.cs:line 27
[03/14/21 07:54:52] [Server API] Error: ===================================================================================
[03/14/21 07:54:52] [Server API] Error: An unhandled exception has occured in TSAPI, and a crash report will be generated
[03/14/21 07:54:52] [Server API] Error: Generating a crash report, please wait...
[03/14/21 07:54:53] [Server API] Error: Could not generate a crash report.
[03/14/21 07:54:53] [Server API] Error: Please upload the crash file and report it at http://tshock.co/
[03/14/21 07:54:53] [Server API] Error: The process will terminate.
[03/14/21 07:54:53] [Server API] Error: ===================================================================================

```

#### Any screenshots?

!!!!!! PLEASE FILL IN THE TEMPLATE ABOVE THANK YOU VERY MUCH !!!!!!

**Comment by csmir** [comment]
Do you have Newtonsoft.Json.dll in your ServerPlugins directory?

**Comment by JottaR** [comment]
no, bu now i put the file and i get this error : 

=====
2021-03-15 12:50:24 - Utils: INFO: Mem executed: .permabuff.
2021-03-15 12:50:24 - Command: ERROR: System.MissingMethodException: Method not found: 'TShockAPI.DB.User TShockAPI.TSPlayer.get_User()'.
   at Permabuffs_V2.Permabuffs.PBuffs(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)
=====

**Comment by bartico6** [comment]
The plugin is outdated by several versions.

**Comment by QuiCM** [comment]
Unfortunately this is not a TShock issue. You'll need to find a more updated version of the plugin
