### ISSUE TITLE
MySQL driver doesn't support MariaDB 10.6 due to weird character encoding issue

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#2350]
Someone in Discord reported this one. Apparently MariaDB 10.6 repots back its character encodings as "utf8mb4" or "utf8mb3" and the driver we're using rejects this because it assumes anything that isn't "utf8" is "not supported." The "utf8" term is deprecated and really the more specific term "utf8mb4" should be used but the driver doesn't recognize this as valid.

The user was able to downgrade to 10.4 to use MariaDB successfully. We tried converting the database's encoding and other parameters to no avail, but downgrading MariaDB did solve the problem. It's important to note that by default, it seemed to boot with the wrong charset and that had to be manually changed in configuration files. So that's not ideal, but even after swapping every character set to utf8mb4, it didn't work. To be precise, in 10.4, the MariaDB server reports back "utf8" but in 10.6, it reports back more specific data instead of that.

The user also reported they tried to upgrade the driver but it didn't do anything. I'm not sure how verbose this test was, though. I **suspect** that upgrading the driver would make it work but I'm not sure.

```
2021-05-27 00:12:00 - ServerApi: INFO: TShock was improperly shut down. Please use the exit command in the future to prevent this.
2021-05-27 00:12:00 - ServerApi: INFO: Loading database...
2021-05-27 00:12:02 - ServerApi: ERROR: Fatal Startup Exception
2021-05-27 00:12:02 - ServerApi: ERROR: System.Exception: Fatal TShock initialization exception: failed to connect to MySQL database. See inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException: Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException: Character set 'utf8mb3' is not supported by .Net Framework.
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String CharSetName)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
   --- End of inner exception stack trace ---
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.DB.SqlTableCreator.GetColumns(SqlTable table)
   at TShockAPI.DB.SqlTableCreator.EnsureTableStructure(SqlTable table)
   at TShockAPI.DB.BanManager..ctor(IDbConnection db)
   at TShockAPI.TShock.Initialize()
```

**Comment by tmzasz** [comment]
this needs to be looked at and not ignored
