### ISSUE TITLE
Update manager warning: The SSL connection could not be established

### ISSUE THREAD

**Issue by TomAltonator** [Pryaxis/TShock#2856]
Running my server as standard. No plugins or mods.
Using latest version and everything is up to date as far as i'm aware.

I ran into this error being outputted by the console every so often.

> 2022-12-02 10:35:19 - <CheckForUpdatesAsync>d__4: WARNING: UpdateManager warning: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TShockAPI.UpdateManager.ServerIsOutOfDateAsync() in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 112
   at TShockAPI.UpdateManager.UpdateCheckAsync(Object o) in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 99
   at TShockAPI.UpdateManager.CheckForUpdatesAsync(Object state) in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 74
2022-12-02 10:35:19 - <CheckForUpdatesAsync>d__4: ERROR: Retrying in 5 minutes.

Do i need to worry about this error?

**Comment by TomAltonator** [comment]
SSC is enabled if that matters at all.

**Comment by sgkoishi** [comment]
Because the server is down temporarily so it failed to check for updates.

**Comment by hakusaro** [comment]
> Because the server is down temporarily so it failed to check for updates.

It is not supposed to be down.

**Comment by hakusaro** [comment]
@TomAltonator thank you for reporting this! I will examine the settings and see what’s wrong.

**Comment by sgkoishi** [comment]
> > Because the server is down temporarily so it failed to check for updates.
> 
> It is not supposed to be down.

Not quite sure but same report since [yesterday on Discord](https://ptb.discord.com/channels/479657350043664384/479657350043664386/1048006713283989557) and other community - the non-HTTPS version works fine but https://update.tshock.co/latest/ is not working.

**Comment by TomAltonator** [comment]
> > > Because the server is down temporarily so it failed to check for updates.
> > 
> > 
> > It is not supposed to be down.
> 
> Not quite sure but same report since [yesterday on Discord](https://ptb.discord.com/channels/479657350043664384/479657350043664386/1048006713283989557) and other community - the non-HTTPS version works fine but https://update.tshock.co/latest/ is not working.

Yes i noticed this too. Chrome warns me that the https version is not online.

**Comment by hakusaro** [comment]
We have a ticket open with our CDN provider, bunny.net. All of tshock.co is affected.

**Comment by hakusaro** [comment]
This should be fixed now. Our CDN provider, bunny.net, got back to me today. I verified that it now works. You should have both TLS and non-TLS working on the update server. If you continue to experience issues, please let me know immediately.
 
<img width="881" alt="Screenshot 2022-12-04 at 10 39 45" src="https://user-images.githubusercontent.com/532647/205509177-8fbe856b-8b10-42dc-9498-16a78b86fa4b.png">

**Comment by TomAltonator** [comment]
Just got this again.
2022-12-17 12:28:31 - <CheckForUpdatesAsync>d__4: WARNING: UpdateManager warning: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TShockAPI.UpdateManager.ServerIsOutOfDateAsync() in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 112
   at TShockAPI.UpdateManager.UpdateCheckAsync(Object o) in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 99
   at TShockAPI.UpdateManager.CheckForUpdatesAsync(Object state) in /home/runner/work/TShock/TShock/TShockAPI/UpdateManager.cs:line 74
2022-12-17 12:28:31 - <CheckForUpdatesAsync>d__4: ERROR: Retrying in 5 minutes.

**Comment by TomAltonator** [comment]
Not the same error, but thought i should let you guys know
