### ISSUE TITLE
Fail to connect to mysql DB but DB exist and wotks fine 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [Pryaxis/TShock#3043]
```
<!-- Please provide the information requested below -->

TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.4.9 (279), OTAPI 1.4.4.9)

[TShock] Info Config path has been set to /terraria/config

[TShock] Info Log path has been set to /terraria/logs

TShock was improperly shut down. Please use the exit command in the future to prevent this.

TShock encountered a problem from which it cannot recover. The following message may help diagnose the problem.

Until the problem is resolved, TShock will not be able to start (and will crash on startup).

System.Exception: Fatal TShock initialization exception: failed to connect to MySQL database. See inner exception for details.

 ---> System.InvalidCastException: Object cannot be cast from DBNull to other types.

   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)

   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)

   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)

   at MySql.Data.MySqlClient.MySqlConnection.Open()

   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 67

   --- End of inner exception stack trace ---

   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 79

   at TShockAPI.DB.SqlTableCreator.GetColumns(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 90

   at TShockAPI.DB.SqlTableCreator.EnsureTableStructure(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 58

   at TShockAPI.DB.BanManager..ctor(IDbConnection db) in /home/runner/work/TShock/TShock/TShockAPI/DB/BanManager.cs:line 77

   at TShockAPI.TShock.Initialize() in /home/runner/work/TShock/TShock/TShockAPI/TShock.cs:line 369

Created new 8401x2401 DefaultCollection`1 for source: System.Void Terraria.Main::.cctor()



```

**Comment by sgkoishi** [comment]
MySQL 8.x? Somehow remember reports about broken 8.x

**Comment by jpVm5jYYRE1VIKL** [comment]
Hi 
Nope . I using Mariadb .  In previous bersions of tshock which is mono based everything worked good. After upgrade to core based not work anymore

**Comment by RainyLens** [comment]
Same issue here on newer version.
Environment:

TShock 5.2 / TerrariaAPI 2.1.0.0 (Protocol v1.4.5.5, OTAPI 3.3.10)
MariaDB 11.2.2 (mariadb.org binary distribution) on Windows Server 2022 (20348.4405)
Connection via localhost (127.0.0.1:3306)

`InvalidCastException` occurs inside `MySql.Data.MySqlClient.Driver.LoadCharacterSetsAsync`,
which executes `SHOW COLLATION` during connection initialization. In MariaDB 10.10+, `INFORMATION_SCHEMA.COLLATIONS` has nullable ID (bigint, NULL) and CHARACTER_SET_NAME (varchar, NULL) columns due to the addition of Unicode 14 collations (e.g., uca1400_ai_ci). The MySql.Data driver does not check for DBNull before casting these values, resulting in the crash.

This is a known and unpatched bug in MySQL Connector/NET ([MySQL Bug #109331](https://bugs.mysql.com/bug.php?id=109331)). Oracle has indicated in multiple bug reports (e.g., [#107452](https://bugs.mysql.com/bug.php?id=107452), [#109331](https://bugs.mysql.com/bug.php?id=109331)) that their development is focused on MySQL Server and they do not extend support to MariaDB-specific issues.

Replacing MySql.Data with MySqlConnector would resolve this, though the migration cost (behavioral differences, dependency chain, regression testing) is a consideration. Alternatively, downgrading MariaDB below 10.10 works as a temporary workaround. This is also related to #2350.

```plaintext
Error Logging Enabled.
[OTAPI] Starting up (PC Server,3.3.10+ed0eaf5,ModFw:1.1.15+a2c0c70).
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.5.5 (318), OTAPI 3.3.10+ed0eaf5)
TShock encountered a problem from which it cannot recover. The following message may help diagnose the problem.
Until the problem is resolved, TShock will not be able to start (and will crash on startup).
System.Exception: Fatal TShock initialization exception: failed to connect to MySQL database. See inner exception for details.
 ---> System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider) in System.Private.CoreLib.dll:token 0x600111c+0xa
   at MySql.Data.MySqlClient.Driver.LoadCharacterSetsAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6000e28+0xdf
   at MySql.Data.MySqlClient.Driver.ConfigureAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6000e25+0x228
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6001071+0x63b
   at MySql.Data.MySqlClient.MySqlConnection.Open() in MySql.Data.dll:token 0x600106f+0x12
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 72
   --- End of inner exception stack trace ---
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 84
   at TShockAPI.DB.SqlTableCreator.GetColumns(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 96
   at TShockAPI.DB.SqlTableCreator.EnsureTableStructure(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 59
   at TShockAPI.SqlLog..ctor(IDbConnection db, String textlogFilepath, Boolean clearTextLog) in /home/runner/work/TShock/TShock/TShockAPI/SqlLog.cs:line 78
   at TShockAPI.TShock.Initialize() in /home/runner/work/TShock/TShock/TShockAPI/TShock.cs:line 329
```

**Comment by RainyLens** [comment]
same at newer , 1.4.5.6
```
[OTAPI] Starting up (PC Server,3.3.11+c532c59,ModFw:1.1.15+a2c0c70).
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.5.6 (319), OTAPI 3.3.11+c532c59)
TShock encountered a problem from which it cannot recover. The following message may help diagnose the problem.
Until the problem is resolved, TShock will not be able to start (and will crash on startup).
System.Exception: Fatal TShock initialization exception: failed to connect to MySQL database. See inner exception for details.
 ---> System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider) in System.Private.CoreLib.dll:token 0x600111c+0xa
   at MySql.Data.MySqlClient.Driver.LoadCharacterSetsAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6000e28+0xdf
   at MySql.Data.MySqlClient.Driver.ConfigureAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6000e25+0x228
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken) in MySql.Data.dll:token 0x6001071+0x63b
   at MySql.Data.MySqlClient.MySqlConnection.Open() in MySql.Data.dll:token 0x600106f+0x12
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 72
   --- End of inner exception stack trace ---
   at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args) in /home/runner/work/TShock/TShock/TShockAPI/Extensions/DbExt.cs:line 84
   at TShockAPI.DB.SqlTableCreator.GetColumns(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 96
   at TShockAPI.DB.SqlTableCreator.EnsureTableStructure(SqlTable table) in /home/runner/work/TShock/TShock/TShockAPI/DB/SqlTable.cs:line 59
   at TShockAPI.SqlLog..ctor(IDbConnection db, String textlogFilepath, Boolean clearTextLog) in /home/runner/work/TShock/TShock/TShockAPI/SqlLog.cs:line 78
   at TShockAPI.TShock.Initialize() in /home/runner/work/TShock/TShock/TShockAPI/TShock.cs:line 329
```

**Comment by hakusaro** [comment]
MariaDB is not supported -- are you using MySQL?

**Comment by RainyLens** [comment]
It have worked with maria (but not now haha), So I'm considering migrating to postgre. It should be work.

**Comment by hakusaro** [comment]
We’re open to suggestions or fixes but support is difficult because we didn’t intend Maria intentionally

**Comment by RainyLens** [comment]
I have successfully migrated to PostgreSQL, moved all my data. works fine.
I am sharing the steps I took here, hoping it serves as a useful reference for others in a similar situation.
Thank you for your time and interest in this Issue. <3
