### ISSUE TITLE
Issue with TShock v4.1.0.0926

### ISSUE THREAD

**Issue by mattw24** [Pryaxis/TShock#539]
As soon as I open up the TerrariaServer.exe it crashs

2013-09-26 15:56:44 - TShock: ERROR: Fatal Startup Exception
2013-09-26 15:56:44 - TShock: ERROR: System.Exception: Could not find a database library (probably Sqlite3.dll)
   at TShockAPI.DB.BanManager..ctor(IDbConnection db)
   at TShockAPI.TShock.Initialize()

**Comment by Noski41406** [comment]
Olink, I literally just joined GitHub to come back here and say you're a ****.
